env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react-hooks/recommended'
plugins:
  - 'react'
  - '@typescript-eslint'
  - 'react-hooks'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: 'module'
rules:
  indent:
    - 'error'
    - 2
  linebreak-style:
    - 'error'
    - 'windows'
  quotes:
    - 'error'
    - 'single'
  semi:
    - 'error'
    - 'always'
