version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/apps/client'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/services/server'
    schedule:
      interval: 'weekly'
