volumes:
  vl-db:
  vl-activemq:

services:
  vl-app:
    depends_on:
      vl-db:
        condition: service_healthy
    container_name: vl-app
    profiles:
      - build
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '3030:3030'
    expose:
      - '3000'
      - '3030'
  vl-db:
    container_name: vl-db
    profiles:
      - local
    image: mysql:8.4
    command: --mysql-native-password=ON
    environment:
      MYSQL_DATABASE: 'verseledger-app'
      MYSQL_USER: 'verseledger-app'
      MYSQL_PASSWORD: 'verseledger-password'
      MYSQL_ROOT_PASSWORD: 'verseledger-password'
    ports:
      - '3306:3306'
    healthcheck:
      test: "mysql $$MYSQL_DATABASE -uroot -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1;'"
      interval: 1s
      timeout: 30s
      retries: 10
      start_period: 10s
    expose:
      - '3306'
    volumes:
      - vl-db:/var/lib/mysql
  vl-rabbitmq:
    depends_on:
      vl-db:
        condition: service_healthy
    container_name: vl-rabbitmq
    profiles:
      - local
    image: rabbitmq:4-management
    ports:
      - '61616:61613'
      - '5672:5672'
      - '15672:15672'
      - '15674:15674'
    expose:
      - '5672'
      - '15672'
      - '61616'
      - '15674'
    volumes:
      - ./rabbit/rabbit.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbit/enabled_plugins:/etc/rabbitmq/enabled_plugins
  vl-adminer:
    depends_on:
      vl-db:
        condition: service_healthy
    container_name: vl-adminer
    profiles:
      - local
    image: adminer
    restart: always
    ports:
      - 8181:8080
