databaseType = "MySql"
name = "vl-db"
id = "853ac828-9b57-405f-9c7c-d6ed806abb82"

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"
schemaModel = "./schema-model"

[redgateCompare]
filterFile = "filter.rgf"

[flyway]
baselineVersion = 0
mixed = true
outOfOrder = false
locations = [ "filesystem:./migrations" ]
validateMigrationNaming = true
