ALTER TABLE `users`
ADD COLUMN `last_login` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE TABLE IF NOT EXISTS `announcements` (
  `id` VARCHAR(26) NOT NULL,
  `content` TEXT NOT NULL,
  `actions` JSON NULL,
  `expireAt` DATETIME NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);
CREATE TABLE IF NOT EXISTS `subscriptions` (
  `id` VARCHAR(26) NOT NULL,
  `user_id` VARCHAR(26) NOT NULL,
  `endpoint` VARCHAR(255) NOT NULL,
  `auth` VARCHAR(255) NOT NULL,
  `p256dh` VARCHAR(255) NOT NULL,
  `expiration_time` INT UNSIGNED NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
