CREATE TABLE IF NOT EXISTS `user_settings` (
  `id` VARCHAR(255) NOT NULL,
  `user_id` VARCHAR(26) NOT NULL,
  `key` VARCHAR(128) NOT NULL,
  `value` VARCHAR(255) NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `user_settings_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
)
