CREATE TABLE IF NOT EXISTS `api_tokens` (
  `id` VARCHAR(26) NOT NULL,
  `user_id` VARCHAR(26) NOT NULL,
  `token_id` VARCHAR(26) NOT NULL,
  `type` ENUM('access','refresh','api') NOT NULL,
  `name` VARCHAR(32) NOT NULL DEFAULT "USER TOKEN",
  `expiresAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `api_tokens_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);
DROP EVENT IF EXISTS `purge_expired_tokens`;
DROP TABLE IF EXISTS `invalid_tokens`;
DELIMITER;;
CREATE EVENT IF NOT EXISTS `purge_expired_validation` ON SCHEDULE EVERY '1' HOUR ON COMPLETION PRESERVE ENABLE COMMENT '' DO
DELETE FROM `user_validation`
WHERE `expiresAt` < NOW();;
DELIMITER;
DELIMITER;;
CREATE EVENT IF NOT EXISTS `purge_expired_api_tokens` ON SCHEDULE EVERY '5' MINUTE ON COMPLETION PRESERVE ENABLE COMMENT '' DO
DELETE FROM `api_tokens`
WHERE `expiresAt` < NOW();;
DELIMITER;
