CREATE TABLE IF NOT EXISTS `user_settings` (
  `id` VARCHAR(26) NOT NULL,
  `user_id` VARCHAR(26) NOT NULL,
  `soundPack` VARCHAR(32) NOT NULL DEFAULT 'systemDefault',
  `theme` VARCHAR(32) NOT NULL DEFAULT 'VerseOS',
  `userPageImage` VARCHAR(32) NOT NULL DEFAULT 'pioneer',
  `animations` VARCHAR(32) NOT NULL DEFAULT 'all',
  `quality` VARCHAR(32) NOT NULL DEFAULT 'high',
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `user_settings_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
)