CREATE TABLE IF NOT EXISTS `feature_flags` (
  `id` VARCHAR(26) NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  `description` VARCHAR(128) NOT NULL,
  `enabled` BOOLEAN NOT NULL DEFAULT 0,
  `percentageOfUsers` VARCHAR(26) NULL,
  `settingName` VARCHAR(128) NULL,
  `settingValue` VARCHAR(255) NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE (`name`)
);
