ALTER TABLE `users`
ADD COLUMN `last_login` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE TABLE IF NOT EXISTS `announcements` (
  `id` VARCHAR(26) NOT NULL,
  `content` TEXT NOT NULL,
  `actions` JSON NULL,
  `expireAt` DATETIME NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);
