CREATE TABLE IF NOT EXISTS `donations` (
  `id` VARCHAR(26) NOT NULL,
  `display_name` VARCHAR(128) NOT NULL,
  `cents` INT NOT NULL,
  `message` TEXT NULL,
  `donation_id` VARCHAR(128) NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);
