CREATE TABLE IF NOT EXISTS `locations` (
  `id` VARCHAR(26) NOT NULL,
  `version` VARCHAR(128) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `category` VARCHAR(64) NOT NULL,
  `parent` VARCHAR(64) NULL,
  `short_name` VARCHAR(64) NOT NULL,
  `waypoint_name` VARCHAR(64) NULL,
  `time_index` VARCHAR(64) NULL,
  `x` DOUBLE NOT NULL,
  `y` DOUBLE NOT NULL,
  `z` DOUBLE NOT NULL,
  `QT` BOOLEAN NOT NULL DEFAULT 0,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);
