name: Bug Report
description: File a bug report for VerseLedger beta
title: "Bug Report"
projects: ["Verse Ledger"]
body:
  - type: markdown
    attributes:
      value: |
        # Bug Report

        Thank you for taking the time to fill out this bug report!
        Please provide as much detail as possible to help us understand and resolve the issue.

        ---
  - type: input
    id: userTitle
    attributes:
      label: Issue Title
      description: Please provide a short, direct title for your issue.
      placeholder: "Nulling Field Error"
    validations:
      required: true
  - type: textarea
    id: brief
    attributes:
      label: Short Description
      description: Please provide a brief description of the issue.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Impacted Area

        Please select the impacted feature and specific tool below.
  - type: dropdown
    id: feature
    attributes:
      label: Impacted Feature
      description: Please select the Feature that you experienced a problem with.
      multiple: false
      options:
        - Contract Ledger
        - Personal Ledger
        - Popup
        - User Settings
        - App Bar
        - Other
  - type: dropdown
    id: tool
    attributes:
      label: Specific Tool
      description: If a specific tool caused this please choose it from the list available.
      multiple: false
      options:
        - Contract Manager
        - Overview App
        - Create Contract
        - Feedback Popup
        - Contract Bids
        - Notifications
        - Filters
        - Other
  - type: markdown
    attributes:
      value: |
        ## Browser

        Please select the browser(s) you used to reproduce the issue.
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Please select the browser(s) you used to reproduce the issue.
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
  - type: markdown
    attributes:
      value: |
        ## Behaviors

        Please describe the behaviors you are experiencing below in great detail.
  - type: textarea
    id: observed
    attributes:
      label: Observed Behavior
      description: Please provide a detailed description of what you experienced with the steps to reproduce the issue.
      placeholder: "When I click on the 'Create Contract' button, I get a Nulling Field Error"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Please provide a detailed description of what you expected to happen.
      placeholder: "I expected the 'Create Contract' button to work"
    validations:
      required: false
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Behavior
      description: Feel free to provide suggested behaviors for this to improve the functionality and perhaps work around the issue or fix it.
      placeholder: "Please suggest any behavior improvements here."
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Logs

        Please provide any logs you gathered for your issue.
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please provide logs for your issue.
      render: shell
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Attachments

        Please provide any screenshots or other files that you think might be helpful.
  - type: textarea
    id: screenshots
    attributes:
      label: Attachments
      description: Please provide screenshots or other files that you think might be helpful.
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Feel free to provide any additional notes you think might be helpful.
      render: markdown
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thank you for your time in completing this bug report!
