volumes:
  vl-db:

services:
  db:
    profiles:
      - local
    image: mysql:latest
    container_name: vl-db
    command: --authentication_policy=mysql_native_password
    environment:
      MYSQL_DATABASE: 'verseledger-app'
      MYSQL_USER: 'verseledger-app'
      MYSQL_PASSWORD: 'vl-password'
      MYSQL_ROOT_PASSWORD: 'vl-password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - vl-db:/var/lib/mysql
  adminer:
    profiles:
      - local
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8181:8080
  backend:
    profiles:
      - build
    build:
      context: ./
      dockerfile: Dockerfile
