import { Contracts, Exploration, Fleet, Rrr, Vehicles } from '@Assets/Images/CustomIcons';
import {
  AccountBalanceTwoTone,
  BusinessTwoTone,
  ConstructionTwoTone,
  ExploreTwoTone,
  GroupsTwoTone,
  GroupTwoTone,
  GroupWorkTwoTone,
  HomeTwoTone,
  HubTwoTone,
  InventoryTwoTone,
  LocalMallTwoTone,
  MenuBookTwoTone,
  NewspaperTwoTone,
  PersonTwoTone,
  RouteTwoTone,
  SchoolTwoTone,
  SettingsTwoTone,
  ShoppingBasketTwoTone,
  StackedBarChartTwoTone,
  StorefrontTwoTone,
  StoreTwoTone,
  WorkTwoTone,
} from '@mui/icons-material';
import type { AppListing } from '@Types/apps';
import { useMemo } from 'react';

export const useMasterAppList = () => {
  // TODO: Setup Feature Flag
  const masterAppList: AppListing[] = useMemo(
    () => [
      {
        id: 'verse-news',
        label: '@APP.NEWS.LABEL',
        path: '/verse-news',
        disabled: false,
        icon: NewspaperTwoTone,
        versionLabel: 'Verse News',
        version: '0.X',
        severityCode: 10,
        category: ['core'],
      },
      {
        id: 'wiki',
        label: '@APP.WIKI.LABEL',
        path: '/support',
        disabled: true,
        icon: SchoolTwoTone,
        versionLabel: 'Wiki',
        version: '0.0.1',
        severityCode: 10,
        category: ['core'],
      },
      {
        id: 'dashboard',
        label: '@APP.HOME.LABEL',
        path: '/apps/dashboard',
        icon: HomeTwoTone,
        versionLabel: 'Dashboard',
        version: '2.0',
        severityCode: 5,
        category: ['core', 'personal'],
      },
      {
        id: 'profile',
        label: '@APP.PROFILE.LABEL',
        path: `/user/${undefined}`,
        icon: PersonTwoTone,
        versionLabel: 'Profile',
        disabled: true,
        version: '0.2',
        severityCode: 8,
        category: ['personal'],
      },
      {
        id: 'relations',
        label: '@APP.RELATIONS.LABEL',
        path: '/apps/relations',
        icon: GroupTwoTone,
        disabled: true,
        versionLabel: 'Relations',
        version: '0.x',
        severityCode: 10,
        category: ['personal'],
      },
      {
        id: 'settings',
        label: '@APP.SETTINGS.LABEL',
        path: '/settings',
        icon: SettingsTwoTone,
        versionLabel: 'Settings',
        version: '2.0.1',
        severityCode: 5,
        category: ['core', 'personal'],
      },
      {
        id: 'explore',
        label: '@APP.EXPLORE.LABEL',
        path: '/apps/explore',
        disabled: true,
        icon: Exploration,
        versionLabel: 'Explorer Tool',
        version: '1.0.0',
        severityCode: 9,
        category: ['personal', 'tool'],
      },
      {
        id: 'routes',
        label: '@APP.ROUTES.LABEL',
        path: '/apps/routes',
        disabled: true,
        icon: RouteTwoTone,
        versionLabel: 'Route Tool',
        version: '2.0.5',
        severityCode: 8,
        category: ['personal', 'tool'],
      },
      {
        id: 'inventory',
        label: '@APP.INVENTORY.LABEL',
        path: '/apps/inventory',
        icon: InventoryTwoTone,
        disabled: true,
        versionLabel: 'Inventory',
        version: '0.x',
        severityCode: 10,
        category: ['personal', 'tool'],
      },
      {
        id: 'ship',
        label: '@APP.SHIP.LABEL',
        path: '/apps/ship',
        icon: Vehicles,
        disabled: true,
        versionLabel: 'Ship Manager',
        version: '0.x',
        severityCode: 10,
        category: ['personal', 'tool'],
      },
      {
        id: 'fleet',
        label: '@APP.FLEET.LABEL',
        path: '/apps/fleet',
        icon: Fleet,
        disabled: true,
        versionLabel: 'Fleet Manager',
        version: '0.x',
        severityCode: 10,
        category: ['personal', 'tool'],
      },
      {
        id: 'builder',
        label: '@APP.BUILDER.LABEL',
        path: '/apps/builder',
        icon: ConstructionTwoTone,
        disabled: true,
        versionLabel: 'Ship Builder',
        version: '0.x',
        severityCode: 10,
        category: ['personal', 'tool'],
      },
      {
        id: 'tuning',
        label: '@APP.TUNING.LABEL',
        path: '/apps/tuning',
        disabled: true,
        icon: StackedBarChartTwoTone,
        versionLabel: 'Tuning Tool',
        version: '0.2',
        severityCode: 9,
        category: ['personal', 'tool'],
      },
      {
        id: 'contracts',
        label: '@APP.CONTRACTS.LABEL',
        path: '/apps/contracts',
        icon: Contracts,
        versionLabel: 'Contract Manager',
        version: '3.1.1',
        severityCode: 1,
        category: ['personal', 'contract'],
      },
      {
        id: 'contract-ledger',
        label: '@APP.LEDGER.LABEL',
        path: '/apps/ledger',
        icon: MenuBookTwoTone,
        versionLabel: 'Contract Ledger',
        version: '2.5',
        severityCode: 2,
        category: ['personal', 'tool', 'core'],
      },
      {
        id: 'contract-service',
        label: '@APP.SERVICES.LABEL',
        path: '/apps/services',
        icon: Rrr,
        versionLabel: 'Services',
        version: '0.0.1',
        severityCode: 9,
        disabled: true,
        category: ['personal', 'contract'],
      },
      {
        id: 'orders',
        label: '@APP.ORDERS.LABEL',
        path: '/apps/orders',
        icon: ShoppingBasketTwoTone,
        disabled: true,
        versionLabel: 'Order Manager',
        version: '0.x',
        severityCode: 10,
        category: ['personal', 'market'],
      },
      {
        id: 'verse-market',
        label: '@APP.MARKET.LABEL',
        path: '/apps/verse-market',
        disabled: true,
        icon: StoreTwoTone,
        versionLabel: 'Verse Market',
        version: '0.x',
        severityCode: 9,
        category: ['personal', 'market', 'core'],
      },
      {
        id: 'org-dash',
        label: '@APP.HOME.LABEL',
        path: '/orgs/dash',
        icon: BusinessTwoTone,
        disabled: true,
        versionLabel: 'Org Dashboard',
        version: '0.0.2',
        severityCode: 10,
        category: ['org', 'personal'],
      },
      {
        id: 'org-relations',
        label: '@APP.RELATIONS.LABEL',
        path: '/orgs/relations',
        icon: GroupsTwoTone,
        disabled: true,
        versionLabel: 'Org Relations',
        version: '0.x',
        severityCode: 10,
        category: ['org'],
      },
      {
        id: 'org-manage',
        label: '@APP.MANAGEMENT.LABEL',
        path: '/orgs/manage',
        icon: GroupWorkTwoTone,
        disabled: true,
        versionLabel: 'Org Management',
        version: '0.0.2',
        severityCode: 10,
        category: ['org', 'tool'],
      },
      {
        id: 'org-contracts',
        label: '@APP.CONTRACTS.LABEL',
        path: '/orgs/contracts',
        icon: WorkTwoTone,
        disabled: true,
        versionLabel: 'Org Contracts',
        version: '0.x',
        severityCode: 10,
        category: ['org', 'contract'],
      },
      {
        id: 'org-pay',
        label: '@APP.PAYROLL.LABEL',
        path: '/orgs/payroll',
        icon: AccountBalanceTwoTone,
        disabled: true,
        versionLabel: 'Org Payroll',
        version: '0.x',
        severityCode: 10,
        category: ['org', 'market', 'contract', 'tool'],
      },
      {
        id: 'org-explore',
        label: '@APP.EXPLORE.LABEL',
        path: '/orgs/explore',
        icon: ExploreTwoTone,
        disabled: true,
        versionLabel: 'Org Explorer',
        version: '0.x',
        severityCode: 10,
        category: ['org', 'tool'],
      },
      {
        id: 'org-fleet',
        label: '@APP.FLEET.LABEL',
        path: '/orgs/fleet',
        icon: Fleet,
        disabled: true,
        versionLabel: 'Org Fleet',
        version: '0.x',
        severityCode: 10,
        category: ['org', 'tool'],
      },
      {
        id: 'org-find',
        label: '@APP.FINDER.LABEL',
        path: '/orgs/finder',
        icon: HubTwoTone,
        disabled: true,
        versionLabel: 'Org Finder',
        version: '0.0.2',
        severityCode: 10,
        category: ['org', 'tool'],
      },
      {
        id: 'org-orders',
        label: '@APP.ORDERS.LABEL',
        path: '/orgs/orders',
        icon: LocalMallTwoTone,
        disabled: true,
        versionLabel: 'Org Orders',
        version: '0.x',
        severityCode: 10,
        category: ['org', 'market'],
      },
      {
        id: 'org-market',
        label: '@APP.MARKET.LABEL',
        path: '/orgs/market',
        icon: StorefrontTwoTone,
        disabled: true,
        versionLabel: 'Org Market',
        version: '0.x',
        severityCode: 10,
        category: ['org', 'market'],
      },
      {
        id: 'org-inventory',
        label: '@APP.INVENTORY.LABEL',
        path: '/orgs/inventory',
        icon: AccountBalanceTwoTone,
        disabled: true,
        versionLabel: 'Org Inventory',
        version: '0.x',
        severityCode: 10,
        category: ['org', 'market'],
      },
    ],
    [],
  );
  return masterAppList;
};
