import { IContractSubType } from 'vl-shared/src/schemas/ContractSubTypeSchema';

export enum QueryNames {
  SortBy = 'sort',
  SortDirection = 'sortDir',
  SearchQuery = 'search',
  ContractManagerTab = 'cmTab',
  Subtype = 'st',
  Locations = 'loc',
  UECRangeMin = 'minUEC',
  UECRangeMax = 'maxUEC',
  Contract = 'contractID',
  EmployerRating = 'eRating',
  ContractorRating = 'cRating',
  Archetype = 'archetype',
  Status = 'status',
  BidStatus = 'bstatus',
  Page = 'page',
  BidBefore = 'bidBefore',
  BidAfter = 'bidAfter',
  bidExact = 'bidExact',
  StartBefore = 'startBefore',
  StartAfter = 'startAfter',
  StartExact = 'startExact',
  EndBefore = 'endBefore',
  EndAfter = 'endAfter',
  EndExact = 'endExact',
  Duration = 'duration',
}
export const ArchetypeToSubtypes: { [key: string]: IContractSubType[] } = {
  Logistics: ['Transport', 'Hauling', 'Manage'],
  Medical: ['Trauma', 'On-Call'],
  Security: ['Escort', 'Bounty', 'QRF', 'Asset-Protection', 'Attache'],
  Salvage: ['Collection', 'Procurement'],
  Industry: ['Mining', 'Refining', 'Manufacturing', 'Scouting'],
  RRR: ['Refuel', 'Rearm', 'Repair'],
  Fleet: ['Crewman', 'Outsourcing'],
  Exploration: ['Locate', 'Charting'],
  Proxy: ['Middleman', 'Redacted'],
};
