export const TYPES = {
  ContractService: Symbol.for('ContractService'),
  AuthService: Symbol.for('AuthService'),
  EnvService: Symbol.for('EnvService'),
  UserService: Symbol.for('UserService'),
  NotificationService: Symbol.for('NotificationService'),
  AuthMiddleware: Symbol.for('AuthMiddleware'),
  VerifiedUserMiddleware: Symbol.for('VerifiedUserMiddleware'),
  StompService: Symbol.for('StompService'),
  TestingMiddleware: Symbol.for('TestingMiddleware'),
  Logger: Symbol.for('Logger'),
  PallyService: Symbol.for('PallyService'),
  ResourceEditorService: Symbol.for('ResourceEditorService'),
  RatingService: Symbol.for('RatingService'),
};
