CREATE TABLE waypoints (
  id VARCHAR(26) PRIMARY KEY,
  owner_id VARCHAR(26),
  parent_id VARCHAR(26) NULL,
  name VARCHAR(64) NOT NULL,
  category VARCHAR(64) NULL,
  x DOUBLE PRECISION DEFAULT 0,
  y DOUBLE PRECISION DEFAULT 0,
  z DOUBLE PRECISION DEFAULT 0
);
