databaseType = "MySql"
name = "unnamed"
id = "853ac828-9b57-405f-9c7c-d6ed806abb82"

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"
schemaModel = "./schema-model"

[redgateCompare]
filterFile = "filter.rgf"

[flyway]
mixed = true
outOfOrder = true
locations = [ "filesystem:migrations" ]
validateMigrationNaming = true

[environments.un-db]
url = "jdbc:mysql://localhost:3306?allowPublicKeyRetrieval=true&useSSL=false"
schemas = [ "unnamed" ]
displayName = "Unnamed DB"
