name: Pipeline
on:
  - pull_request
jobs:
  eslint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: ./.yarn/releases/yarn-1.22.22.cjs install --frozen-lockfile
      - run: ./.yarn/releases/yarn-1.22.22.cjs lint:check
  test:
    runs-on: self-hosted
    needs:
      - eslint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: ./.yarn/releases/yarn-1.22.22.cjs install --frozen-lockfile
      - run: ./.yarn/releases/yarn-1.22.22.cjs test
